-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 01:38:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Schild_Security
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Schild_Security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Schild_Security` ;
USE `Schild_Security` ;

-- -----------------------------------------------------
-- Table `Schild_Security`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schild_Security`.`Usuario` (
  `ID` INT NOT NULL,
  `Nombre` VARCHAR(55) NOT NULL,
  `Apellido` VARCHAR(65) NOT NULL,
  `Email` VARCHAR(65) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Fecha_registro` DATETIME NOT NULL,
  `Foto_perfil` VARCHAR(250) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schild_Security`.`wearables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schild_Security`.`wearables` (
  `ID` INT NOT NULL,
  `serie_wearables` VARCHAR(45) NOT NULL,
  `codigo_activador` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_wearables_Usuario1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_wearables_Usuario1`
    FOREIGN KEY (`id_user`)
    REFERENCES `Schild_Security`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schild_Security`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Schild_Security`.`Location` (
  `ID` INT NOT NULL,
  `ubicacion` VARCHAR(250) NOT NULL,
  `id_user` INT NOT NULL,
  `id_wearables` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Location_Usuario_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_Location_wearables1_idx` (`id_wearables` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `Schild_Security`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_wearables1`
    FOREIGN KEY (`id_wearables`)
    REFERENCES `Schild_Security`.`wearables` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
